name: vg-feature-extraction
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - asttokens=2.2.1
  - attr=2.5.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cairo=1.16.0
  - certifi=2023.7.22
  - comm=0.1.4
  - contourpy=1.1.0
  - cycler=0.11.0
  - dbus=1.13.6
  - debugpy=1.6.8
  - decorator=5.1.1
  - executing=1.2.0
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.42.0
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.76.4
  - glib-tools=2.76.4
  - graphite2=1.3.13
  - gst-plugins-base=1.22.3
  - gstreamer=1.22.3
  - harfbuzz=7.3.0
  - icu=72.1
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - ipykernel=6.25.1
  - ipython=8.14.0
  - jedi=0.19.0
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.69
  - libcblas=3.9.0
  - libclang=16.0.6
  - libclang13=16.0.6
  - libcups=2.3.3
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.1.0
  - libgcrypt=1.10.1
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.4
  - libgomp=13.1.0
  - libgpg-error=1.47
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libllvm16=16.0.6
  - libnsl=2.0.0
  - libogg=1.3.5
  - libopenblas=0.3.23
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libstdcxx-ng=13.1.0
  - libsystemd0=254
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libxkbcommon=1.5.0
  - libxml2=2.11.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mpg123=1.31.3
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - nspr=4.35
  - nss=3.89
  - numpy=1.25.2
  - openjpeg=2.5.0
  - openssl=3.1.2
  - packaging=23.1
  - pandas=2.0.3
  - parso=0.8.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.0
  - pip=23.2.1
  - pixman=0.40.0
  - platformdirs=3.10.0
  - ply=3.11
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - pygments=2.16.1
  - pyparsing=3.0.9
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3
  - pyzmq=25.1.0
  - qt-main=5.15.8
  - readline=8.2
  - setuptools=68.0.0
  - sip=6.7.11
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.2
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - wcwidth=0.2.6
  - wheel=0.41.1
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.39
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.6
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - h5py==3.9.0
      - ts2vg==1.2.2
